//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCCUBH
{
    using System;
    using System.Collections.Generic;
    
    public partial class HANGHOA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HANGHOA()
        {
            this.CHITIETCUNGUNGs = new HashSet<CHITIETCUNGUNG>();
            this.KHANANGs = new HashSet<KHANANG>();
        }
    
        public string MaHangHoa { get; set; }
        public string TenHangHoa { get; set; }
        public string QuyCach { get; set; }
        public string DonViTinh { get; set; }
        public Nullable<int> DonGia { get; set; }
        public string MaLoaiHangHoa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETCUNGUNG> CHITIETCUNGUNGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHANANG> KHANANGs { get; set; }
        public virtual LOAIHANGHOA LOAIHANGHOA { get; set; }
    }
}
