//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCCUBH
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETCUNGUNG
    {
        public string SoPhieu { get; set; }
        public string MaHangHoa { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> ThanhTien { get; set; }
    
        public virtual HANGHOA HANGHOA { get; set; }
        public virtual PHIEUCUNGUNG PHIEUCUNGUNG { get; set; }
    }
}
